language: generic

addons:
  ssh_known_hosts: 77.244.215.202

before_deploy:
- openssl aes-256-cbc -K $encrypted_ed3f86b74059_key -iv $encrypted_ed3f86b74059_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@77.244.215.202:/root/travis-files/lingany-data-access
  on:
    branch: master